### ISSUE TITLE
assign_timepoint function enhancements

### ISSUE THREAD

**Issue by emilyvertosick** [ddsjoberg/hotfun#12]
- Display an error if variable name specified in "new_var" already exists
- Allow for more than one ID variable
- Currently function only outputs id variable, two date variables and new variable with timepoint (drops all other columns) - update so all columns are kept and timepoint column added to the end
- Check that window frame is not width 0 (e.g. show an error if window input is c(1, 1)) or print the width of the windows that so we know
- Add option to include/exclude boundary values (for example, for timepoint 0, only keep those on day 1 and after, not on day 0)

**Comment by ddsjoberg** [comment]
Hey hey @emilyvertosick !

I made the following updates
- [x] Display an error if variable name specified in "new_var" already exists
- [x] Allow for more than one ID variable
- [x] Currently function only outputs id variable, two date variables and new variable with timepoint (drops all other columns) - update so all columns are kept and timepoint column added to the end
- [x] Check that window frame is not width 0 (e.g. show an error if window input is c(1, 1)) or print the width of the windows that so we know
- [ ] Add option to include/exclude boundary values (for example, for timepoint 0, only keep those on day 1 and after, not on day 0)

The last one was a little trickier, so i left it out, but I think it's not too difficult to program around it, e.g. use `1 - 10e-20` instead of 1 when you want `< 1` instead of `<= 1`.


There is no rush, but can review the updates in this PR
https://github.com/ddsjoberg/bstfun/pull/71

**Comment by ddsjoberg** [comment]
improvements added to bstfun
